package types

const (
	PathV1Sign             = "/v1/sign"
	PathHealthz            = "/healthz"
	PathRoot               = "/"
	PathAdmin              = "/admin"
	PathAdminPrefix        = "/admin/"
	PathAdminSnapshot      = "/admin/snapshot"
	PathAdminLeasesPrefix  = "/admin/leases/"
	PathAdminAuthChallenge = "/admin/auth/challenge"
	PathAdminAuthLogin     = "/admin/auth/login"
	PathAdminLogout        = "/admin/logout"
	PathAdminAuthStatus    = "/admin/auth/status"
	PathAdminApproval      = "/admin/settings/approval-mode"
	PathAdminLandingPage   = "/admin/settings/landing-page"
	PathAdminUDP           = "/admin/settings/udp"
	PathAdminTCPPort       = "/admin/settings/tcp-port"
	PathAdminIPsPrefix     = "/admin/ips/"
	PathInstallShell       = "/install.sh"
	PathInstallPowerShell  = "/install.ps1"
	PathInstallBinPrefix   = "/install/bin/"

	PathPublicSnapshot = "/api/public/snapshot"

	PathAgentPrefix        = "/v1/agent"
	PathAgentStatus        = PathAgentPrefix + "/status"
	PathAgentShutdown      = PathAgentPrefix + "/shutdown"
	PathAgentTunnels       = PathAgentPrefix + "/tunnels"
	PathAgentTunnelsPrefix = PathAgentPrefix + "/tunnels/"
	PathAgentAuthChallenge = PathAgentPrefix + "/auth/challenge"
	PathAgentAuthLogin     = PathAgentPrefix + "/auth/login"
	PathAgentAuthLogout    = PathAgentPrefix + "/auth/logout"
	PathAgentAuthStatus    = PathAgentPrefix + "/auth/status"

	PathTunnelStatus    = "/tunnel/status"
	PathThumbnailPrefix = "/thumbnail/"

	PathSDKDomain            = "/sdk/domain"
	PathSDKRegisterChallenge = "/sdk/register/challenge"
	PathSDKRegister          = "/sdk/register"
	PathSDKRenew             = "/sdk/renew"
	PathSDKUnregister        = "/sdk/unregister"
	PathSDKHop               = "/sdk/hop"
	PathSDKConnect           = "/sdk/connect"
	PathDiscovery            = "/discovery"
	PathDiscoveryAnnounce    = "/discovery/announce"

	PathX402Facilitator       = "/x402"
	PathX402FacilitatorPrefix = PathX402Facilitator + "/"
	X402SupportedPath         = PathX402Facilitator + "/supported"
	X402VerifyPath            = PathX402Facilitator + "/verify"
	X402SettlePath            = PathX402Facilitator + "/settle"
)
